pages:
  # 1. Imagen de Docker
  image: maven:latest
  
  # 2. Script
  script:
    # - "chmod +x mvnw"
    - "./mvnw javadoc:javadoc" 
    - "mv target/site/apidocs public"

  artifacts:
    paths:
      - public
      
  rules:
    - if: $CI_COMMIT_BRANCH == "alonso-moros"